apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  namespace: {{ include "originhub.namespace" . }}
type: Opaque
data:
  ORIGINHUB_JWT_SECRET: {{ required "common.secrets.ORIGINHUB_JWT_SECRET is required (base64)" .Values.common.secrets.ORIGINHUB_JWT_SECRET }}
