apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ include "originhub.namespace" . }}
  labels:
    app: originhub-postgres
type: Opaque
data:
  DB_DATABASE: {{ required "postgres.secrets.DB_DATABASE (base64)" .Values.postgres.secrets.DB_DATABASE }}
  DB_USERNAME: {{ required "postgres.secrets.DB_USERNAME (base64)" .Values.postgres.secrets.DB_USERNAME }}
  DB_PASSWORD: {{ required "postgres.secrets.DB_PASSWORD (base64)" .Values.postgres.secrets.DB_PASSWORD }}
