apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: originhub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: originhub
  source:
    repoURL: ORIGINHUB_GIT_REPO_URL
    targetRevision: ORIGINHUB_GIT_REVISION
    path: deploy/helm/originhub
    helm:
      valueFiles:
        - values.yml
        - local.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: originhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
