apiVersion: v1
kind: Service
metadata:
  name: originhub-backend
  namespace: {{ include "originhub.namespace" . }}
  labels:
    app: originhub-backend
spec:
  type: ClusterIP
  selector:
    app: originhub-backend
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
