{{- if .Values.originhub.ssh.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: originhub-backend-ssh
  namespace: {{ include "originhub.namespace" . }}
  labels:
    app: originhub-backend
spec:
  type: {{ .Values.originhub.ssh.serviceType }}
  selector:
    app: originhub-backend
  ports:
    - port: {{ .Values.originhub.ssh.port }}
      name: ssh
      targetPort: {{ .Values.originhub.ssh.port }}
      protocol: TCP
      {{- if and (eq .Values.originhub.ssh.serviceType "NodePort") .Values.originhub.ssh.nodePort }}
      nodePort: {{ .Values.originhub.ssh.nodePort }}
      {{- end }}
{{- end }}
