{{- if and .Values.monitoring.enabled .Values.monitoring.prometheus.enabled .Values.monitoring.prometheus.ingress.enabled .Values.monitoring.prometheus.ingress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: originhub-prometheus
  namespace: {{ include "originhub.namespace" . }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    {{- if .Values.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.monitoring.prometheus.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: originhub-prometheus
                port:
                  number: 9090
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.monitoring.prometheus.ingress.host | quote }}
      secretName: originhub-prometheus-tls-cert
  {{- end }}
{{- end }}
