{{- if and .Values.monitoring.enabled .Values.monitoring.grafana.enabled .Values.monitoring.secrets.GF_SECURITY_ADMIN_PASSWORD }}
apiVersion: v1
kind: Secret
metadata:
  name: originhub-monitoring-secret
  namespace: {{ include "originhub.namespace" . }}
  labels:
    app: originhub-grafana
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.monitoring.secrets.GF_SECURITY_ADMIN_PASSWORD }}
{{- end }}
