{{- if and .Values.frontend.enabled .Values.frontend.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: originhub-frontend
  namespace: {{ include "originhub.namespace" . }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    {{- if .Values.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManager.clusterIssuer | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ .Values.frontend.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: originhub-backend
                port:
                  number: 80
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.frontend.host | quote }}
      secretName: originhub-frontend-tls-cert
  {{- end }}
{{- end }}
