apiVersion: v1
kind: Service
metadata:
  name: originhub-redis
  namespace: {{ include "originhub.namespace" . }}
  labels:
    app: originhub-redis
spec:
  type: ClusterIP
  selector:
    app: originhub-redis
  ports:
    - port: 6379
      name: redis
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: originhub-redis
  namespace: {{ include "originhub.namespace" . }}
  labels:
    app: originhub-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: originhub-redis
  template:
    metadata:
      labels:
        app: originhub-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args: ["redis-server", "--save", "", "--maxmemory", "512mb", "--maxmemory-policy", "volatile-lru"]
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
